### ISSUE TITLE
Scrape from XML feed

### ISSUE THREAD

**Issue by danasilver** [coursereviews/coursereviews#22]
So there's an XML feed with the courses:

Course sections in Fall 2014 (a.k.a. 201490) as a web page:
http://catalog.middlebury.edu/offerings/search/catalog/catalog%2FMCUG?term=term%2F201490&department=&keywords=&time_start=0&time_end=86400&type[]=genera%3Aoffering%2FLCT&type[]=genera%3Aoffering%2FSEM&search=Search

Course sections in Fall 2014 (a.k.a. 201490) as XML:
http://catalog.middlebury.edu/offerings/searchxml/catalog/catalog%2FMCUG?term=term%2F201490&department=&keywords=&time_start=0&time_end=86400&type[]=genera%3Aoffering%2FLCT&type[]=genera%3Aoffering%2FSEM&search=Search

Should be more sustainable and efficient.

**Comment by danasilver** [comment]
Closing since this is being worked on as a separate module at coursereviews/catalog.

**Comment by teddyknox** [comment]
:+1:
