### ISSUE TITLE
Number of reviews badge

### ISSUE THREAD

**Issue by teddyknox** [coursereviews/coursereviews#31]
The user experiences some disappointment when clicking a professor or course from the browse page only to see that the object has no reviews. We could prevent this by putting a badge by the links to professor/course detail pages which would indicate how many reviews that course or professor had. No badge would be present if the object has no reviews. This would greatly increase the computation cost of rendering the browse page, and so to implement this at scale we might need to enable caching.

**Comment by danasilver** [comment]
We now show badges with the number of reviews on the new catalog page. e75bee103b57e7ebe09937acdd1f7011007aeb17
